Look at the exit code

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,7 +25,8 @@ jobs:
       - name: notify
         id: dothenotification
         run: |
-          echo "::set-output name=mayfail::completion"
+          true
+          echo "::set-output name=mayfail::$?"
   evaluate:
     name: evaluate the previous step
     runs-on: ubuntu-latest
